bbatsov/crux

- crux.el
There are still improvements that can be done: 1. Select one of the startup files before open. See http://hyperpolyglot.org/unix-shells#startup-file. 2. Detect shell when the shell is something like /usr/bin/sh.
The string-prefix-p for ksh is due to various names of ksh in different distributions such as ksh88 and ksh93
> Support tcsh, fish and ksh for crux-find-shell-init-file.

- crux.el
`(crux-rename-file-and-buffer)` was incorrectly labeled in the README
so I updated the name and created aliases for the other way to name the
same commands.
> fix file-and-buffer command consistencies and alias inverse

- crux.el
Or it complains 'crux-reopen-as-root: Symbol's function definition is void: tramp-tramp-file-p'.
There is still another way to fix this:
```
(declare-function tramp-tramp-file-p "ext:tramp")
replace (tramp-tramp-file-p buffer-file-name) with (when (require 'tramp nil 'noerror) (tramp-tramp-file-p buffer-file-name))
```
Not sure which way is better. You do the decision.
> Require tramp for `tramp-tramp-file-p`.

- README.md
- crux.el
This is copied directly from
https://www.emacswiki.org/emacs/TransposeWindows, and renamed to
crux-tranpose-windows. The wiki page mentions the original author as
Thomas Bellman. It does not appear to be published in any existing
package that I could find.
> Add crux-transpose-windows for swapping the buffers between two windows

- crux.el
For some languages, we can't call `indent-according-to-mode` as there
are multiple possible indentations. Python is a great example. For these
languages, `electric-indent-inhibit` is `t` to prevent emacs changing
indentation without the user requesting it.
In this situation, we give the new line the same indentation characters as the
current line. This ensures we respect the user's tab/space configuration.
Closes #26.
> When opening a line above, don't reindent the current line

- crux.el
This changes `crux-rename-file-and-buffer` to:
* Let users specify new file names, even if ido/helm are enabled
* Let users create new directories by modifying other parts of the path
Let me know what you think. These are the only features my implementation has when I realised that crux can do this for me. I've separated these two changes into two commits in case you'd prefer only having one of these changes.
> Increase flexibility for inputs to crux-rename-file-and-buffer

- README.md
- crux.el
Currently, opening any file that is read-only and not owned by the
current user triggers a root login prompt. This occurs for viewing
system files (e.g /etc/fstab), built-in elisp
libraries (e.g. simple.el.gz) and simply viewing files owned by other
users on a shared system.
We can't assume that this is the behaviour users want, and changing
built-in functions without asking is surprising.
Fixes #20.
> Don't change default find-file behaviour

- crux.el
This was preventing `package.el` (and hence MELPA) from parsing the package metadata.
> Fix malformed header line

- README.md
- crux.el
By using completing read in crux-recentf-find-file, we can support ido,
helm and ivy users. I've left an alias to avoid breaking current configs.
> Don't assume ido when offering files from recentf

- crux.el
Tabs are not equivalent to spaces in Makefiles, so `untabify` should be suppressed for them. Added a (currently) singleton list of modes, same as per indentation sensitive modes.
> Support make `crux-cleanup-buffer-or-region` support makefiles

- README.md
- crux.el
Similar to `crux-move-beginning-of-line` in that it behaves differently if you press it twice.
I find it super handy and thought I would offer to share it.
I suggest overriding the default `C-k` command with smart-kill-line since the behavior is similar enough I don't miss the default. Do we have a preference about that? I can't think of a better suggested keybinding.
> Add smart kill line function

- crux.el
Defines crux-smart-line-start, a new function to replace back-to-indentation.
back-to-indentation moves the point to the first non-whitespace character. The new function does that for all major modes, except ansi-term and eshell, where it moves to end of the prompt. More major modes can be added.
By fixing this function, crux-move-beginning-of-line is improved. [Prelude issue #998](https://github.com/bbatsov/prelude/issues/998) "C-a broken in eshell" is fixed. There were workarounds posted in that thread, but I thought a better solution was available.
> Beginning line function

- crux.el
Since the system open command appears to fork immediately there shouldn't be any
real performance penalty to doing this.
Fixes #37 
@bbatsov Please test on OSX. I'm not able to.
> Use synchronous process for crux-open-with

- crux.el
Fixes issues described in https://github.com/bbatsov/crux/issues/46
(line-end-position) stops the search from passing through all the
empty lines.
t suppresses the message on search fail, but doesn't move to the line
end. A non nil, non t arg would also suppress the message, but move
to (line-end-position).
> Fixes two issues with crux-move-beginning-line

- crux.el
This makes it so that the sexp is replaced with the actual value. Otherwise, you get a printed version that isn't actually that useful in elisp.
> crux-eval-and-replace: insert literal s-exp instead of printing.

- crux.el
So crux doesn't create two separate customize groups
> Give crux group to crux-reopen-as-root-mode

- README.md
- crux.el
Occasionally I'd like to make an identical copy of a file I'm currently visiting, to a backup location, or to modify slightly. The default copy file mechanism is annoying, firstly it doesn't create the directories on the path that's missing for me, secondly there's no way to preserve permissions and uid interactively.  Lastly, it doesn't visit the newly copied file. This is basically a copy-file-dwim that I've been missing.
> crux-copy-file-preserve-attribute

- README.md
- crux.el
(I promise this is the last of my barrage of PRs)
By default `upcase-region` `downcase-region` and `captialize-region` commands
are disabled in emacs, and for good reason because they are insane. Whenever
you've placed a mark anywhere in the document, inadventently pressing one of the
assigned keybinding will change the cases for all the words in half a
document. These commands resurrect these potentially useful functions in a much
saner way by wrapping them around `use-region-p`, so they are only activated
when `transient-mark-mode` is one.
> Saner functions for modifying cases on region for humans

- crux.el
This adds a new defcustom `crux-shell-func` that can point to any symbol which takes a buffer name and creates a shell.
I've also included conforming implementations for all of the built-in shells for Emacs so users can just set the variable to the one that matches their preferred shell. To add support for new shells is very straight forward. For example to support vterm:
```elisp
(defun crux-vterm (buffer-name)
(vterm (format "*%s*" buffer-name))
(setq crux-shell-func #'crux-vterm)
```
I was unsure about two things:
1. It doesn't look like there's any documentation for the customs beyond their strings, the README doesn't really go in depth on customization options. So I was curious about what if anything should change / be added documentation wise.
2. If I should go ahead and include …
> Support using any shell creating function with crux-visit-term-buffer

- crux.el
I wanted to make `crux-move-beginning-of-line` do what I wanted in `org-mode`. Specifically, that means skipping over whitespace and stars at the beginning of the line. Rather than add another expression within the `cond` in `move-to-mode-line-start`, I thought it was best to rework it for extensibility and add a new variable, `crux-line-start-regex-alist`. Now that I think about it, maybe it should be a `defcustom`. 
Please have a look. Happy to change it however. Thanks!
> Rework `move-to-mode-line-start` to add extensibility.

- README.md
- crux.el
This is complementary to crux-kill-line-backwards, but moving forward,
and when called at end of line, it will join.
> Add function crux-kill-and-join-forward

- crux.el
This way, functions such as `crux-move-beginning-of-line' work as expected when in visual-line mode:
1. If the user runs this function in the middle of a visual line, it will go to the beginning of said visual line.
2. If the user runs this function again, then it will go to the beginning of the real line.
3. If the user runs this function again, then it will go to the first non-space character of the line.
Swapping 2 and 3 may also be an expected behavior but then the code became way more complicated than it should.
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>
> Use `beginning-of-visual-line' in `move-to-mode-line-start'

- crux.el
After renaming `move-to-mode-line-start` to `crux-move-to-mode-line-start` in https://github.com/bbatsov/crux/commit/dcd693c258ae4d867b18d9a028a828ef6c42a4a6 there are still one usage of old `move-to-mode-line-start` function.
Thanks!
> crux-smart-open-line-above: Use crux-move-to-mode-line-start

- CHANGELOG.md
- README.md
- crux.el
Make it easy to kill the path of file visited in the current buffer. I was able to replace most of my own functions with a `crux` equivalent, except for this one.
> Add crux-kill-buffer-truename

- crux.el
Using read-file-name allows completion of file paths while
read-from-minibuffer does not.
Thanks!
> Read file name insead of raw string

- CHANGELOG.md
- README.md
- crux.el
Adds `crux-recentf-find-directory` for opening recent directories. Complements the existing `crux-recentf-find-file`.
---
> Add crux-recentf-find-directory

- crux.el
Hi M.Batsov. 
Here a simple check using `org-element.el` to make `crux-view-url` a little more aware.
> Add support for org-mode links to crux-view-url

- CHANGELOG.md
- README.md
- crux.el
Similar to the existing macros such as crux-with-region-or-line, add a new macro called crux-with-region-or-sexp-or-line, which advises a command so that if it is called with no active region, it is instead called on the current sexp (or string), falling back to the current line.
Note: I found that some of the functions that might been more obvious to use for this didn't work correctly, e.g. `list-at-point` doesn't work with Clojure vectors and sets (but `(thing-at-point 'list)` handles them fine), and `beginning-of-sexp`/`thing-at-point--beginning-of-sexp` move along a single symbol, but not to the beginning of the list.
Thanks!
> Add crux-with-region-or-sexp-or-line

- CHANGELOG.md
- crux.el
Currently if you rename a new buffer that hasn't been saved yet, `crux-rename-file-and-buffer` will only rename the buffer but not reset the visited file name, so saving after renaming will still save to the file name before renaming. The PR also let the user know if we are renaming to an existing buffer.
* Offer to save file first if modified or new unsaved buffer.
* Message user if new file name is the same.
Thanks!
> More robust `crux-rename-file-and-buffer`.

- CHANGELOG.md
- crux.el
`crux-copy-file-preserve-attributes` suffers from several problems:
- A new buffer is always opened without correctly taking into account the value of universal argument
- If filename is different, the new opened buffer contains the source file (destination file in same directory) or an empty buffer (destination file in other directory)
- If the destination chosen by user is a complete path (with filename) in a non-existent directory, the function fails with error "Opening output file: No such file or directory"
So I rewrote the function in a more robust way to to limit mishandled cases.
> More robust crux-copy-file-preserve-attributes

- CHANGELOG.md
- crux.el
Just a little fix to complete previous PR (https://github.com/bbatsov/crux/pull/100).
> Create nonexistent parent directories in `crux-copy-file-preserve-attributes`

- CHANGELOG.md
- README.md
- crux.el
Response to issue #101. Function creates/edits '.dir-locals.el' file in the current directory of the current buffer.
Thanks!
> Add crux-find-current-directory-dir-locals-file
